apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
        - image: {{ .Values.mongo.image }}
          name: mongo
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          resources: {}
      restartPolicy: Always
status: {}