apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-express.fullname" . }}
  labels:
    {{- include "helm-express.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm-express.selectorLabels" . | nindent 4 }}
